### ISSUE TITLE
Move slurm_walltime_to_seconds out of Slurm

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/plurmy#5]
This function does not need to be part of the Slurm object. If all we want to do is change the walltime to seconds it would be useful to just be able to give this a walltime rather than recreating the Slurm object.

**Comment by jlaura** [comment]
I think we have another option, which is to use the `@staticmethod` decorator so that one could do `Slurm.slurm_walltime_to_seconds()` without instantiating the slurm object. This *might* be nice to keep everything in the library under the slurm object. I am not sold though...

**Comment by acpaquette** [comment]
@jlaura The current PR you have (#6) is how I would do it but either or is fine.
